### ISSUE TITLE
Example using pytest

### ISSUE THREAD

**Issue by rdmolony** [marcgibbons/django-selenium-docker#1]
Hi Marc,

Thanks a lot for taking the time to write this up.  You've really helped me out.

I'm currently learning `Django` + `Docker` + `Selenium` and have adapted your example for `pytest` if you or anyone else is interested - https://github.com/rdmolony/django-selenium-pytest-docker

**Comment by marcgibbons** [comment]
Hey @rdmolony just seeing this now! I've updated the repo & blog post to use pytest as well. Thank you 😄
